on:
  push:
    branches:
      - main

name: cPanel Deploy Action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: cPanel Deploy Action
        uses: pinkasey/cpanel-deploy-action@v1.1.2
        with: 
          hostname: ${{ secrets.CPANEL_HOSTNAME }}
          cPanelApiPort: ${{ secrets.CPANEL_API_PORT }}
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          repository_root: '/home/newsblee/repositories/newtest'
          updateRepository: true
          branch: 'main'
